USE [AX_TEST]
GO

declare @INV nvarchar(30) = '170214'	

select 'PPV' VarianceType, 
ITEM, 
RECEIPTDATE DocumentDate, 
PURCHASEORDER, 
INVENTTRANSID, 
INVENTQTY AS QTY,
UNITPOPRICE ReceiptUnitPrice, 
EXTENDEDPOPRICE ReceiptAmount,   
STANDARDCOST [Invoice/STD Unit Cost],  
EXTENDEDSTANDARDCOST [Extended Invoice/STD Unit Cost],  
VARIANCE, 
PACKINGSOURCEDOCUMENTLINE  AS SourceDocumentLine        
	,PACKINGSLIPID
	,INVOICEID
	,VOUCHERPHYSICAL
	,VOUCHERFIN 
from zzzANGINVENTPPV 
where INVOICEID = @INV 


union 


select 'IPV',
T2.ITEM          ,
MAX(T9.INVOICEDATE) AS INVOICEDATE ,
T2.PURCHASEORDER,        
T2.INVENTTRANSID,       
T9.INVENTQTY QTY,                               
MAX(T2.UNITPOPRICE) AS ReceiptUnitPrice   ,
T9.INVENTQTY * AVG(T2.UNITPOPRICE) ReceiptAmount,    
T9.INVOICEPRICE INVOICEPRICE   ,                     
/*T9.INVOICEPRICE *  T9.INVENTQTY*/ LineAmountMST AS [Invoice/STD Unit Cost] ,                   
(T9.INVENTQTY * AVG(T2.UNITPOPRICE)) - LineAmountMST /*(T9.INVOICEPRICE *  T9.INVENTQTY)*/  AS IPVVARIANCE                                
, t9.SOURCEDOCUMENTLINE
,MAX(t2.PACKINGSLIPID) PACKINGSLIPID
,t2.INVOICEID
	,MAX(VOUCHERPHYSICAL) VOUCHERPHYSICAL
	,VOUCHERFIN 

from zzzANGINVENTPPV t2
left JOIN (select INVOICEID,INVOICEDATE,INVENTTRANSID, INVENTQTY INVENTQTY, PurchPrice InvoicePrice, LineAmountMST LineAmountMST, SOURCEDOCUMENTLINE  from VENDINVOICETRANS ) AS T9 on t2.INVENTTRANSID = t9.INVENTTRANSID 
and t2.INVOICEID = t9.INVOICEID
--left join VENDINVOICEPACKINGSLIPQUANTITYMATCH T10 on T10.INVOICESOURCEDOCUMENTLINE = T9.SOURCEDOCUMENTLINE and t10.PACKINGSLIPSOURCEDOCUMENTLINE = t2.PACKINGSOURCEDOCUMENTLINE
where  t2.INVOICEID = @INV

group by T2.ITEM,
T2.PURCHASEORDER,        
T2.INVENTTRANSID,       
T9.INVENTQTY,
T9.INVOICEPRICE,
LineAmountMST,
t9.SOURCEDOCUMENTLINE,
t2.INVOICEID
	--,VOUCHERPHYSICAL
	,VOUCHERFIN 
order by 1, 3,2 
