CHECKPOINT;
GO
DBCC DROPCLEANBUFFERS;
GO

DBCC FREEPROCCACHE;
GO

DBCC FREESYSTEMCACHE ('ALL');
GO

DBCC FREESESSIONCACHE;
GO

DBCC SHRINKFILE (TEMPdev, 15360);   --- New file size in MB
GO

DBCC SHRINKFILE (TEMPDEV2, 15360);   --- New file size in MB
GO
DBCC SHRINKFILE (TEMPDEV3, 15360);   --- New file size in MB
GO
DBCC SHRINKFILE (TEMPDEV4, 15360);   --- New file size in MB
GO
DBCC SHRINKFILE (TEMPDEV5, 15360);   --- New file size in MB
GO
DBCC SHRINKFILE (TEMPDEV6, 15360);   --- New file size in MB
GO
DBCC SHRINKFILE (TEMPDEV7, 15360);   --- New file size in MB
GO
DBCC SHRINKFILE (TEMPDEV8, 15360);   --- New file size in MB
GO